language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_cd1e25f5ca33_key -iv $encrypted_cd1e25f5ca33_iv
  -in test/java/resources/application.properties.enc -out test/java/resources/application.properties -d
